### ISSUE TITLE
mask purpose？

### ISSUE THREAD

**Issue by elvindp** [researchmm/Stark#53]
Hi, in the implementation, a mask with input size is used, which is confused to me. I wonder if there are any paper talked about that. Thanks!

**Comment by MasterBin-IIAU** [comment]
@elvindp Hi, the mask is used to deal with padding. We don't want the network (Transformer) to learn similarity with padding regions because these regions have no valuable information. The mask operation doesn't have obvious influence on the tracking performance.

**Comment by elvindp** [comment]
@MasterBin-IIAU Hi, thanks you for the answer. Another question is that, lightning model does not have score head. Is this because that the performance is bad? And I would like to train with score head,  and I directly use the stark_st1 to train lightening model, which product such error:
`ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/notebook/data/group/wdp/reid/Stark-main/lib/train/../../lib/train/data/sampler.py", line 98, in __getitem__
    return self.getitem()
  File "/home/notebook/data/group/wdp/reid/Stark-main/lib/train/../../lib/train/data/sampler.py", line 108, in getitem
    dataset = random.choices(self.datasets, self.p_datasets)[0]
  File "/opt/conda/lib/python3.7/random.py", line 361, in choices
    raise ValueError('The number of weights does not match the population')
ValueError: The number of weights does not match the population
`

**Comment by TsingWei** [comment]
@elvindp 

> 3. Without the score, if the target is out of FOV (i.e. out of image), the lightning model will always product a wrong output coordinate.
Yeah, it is annoying. This design limits the deployment of STARK.
