### ISSUE TITLE
Problem of Training for Stark-Lighting-X-trt

### ISSUE THREAD

**Issue by sumzora** [researchmm/Stark#92]
Hello, when I use the command "python tracking/train.py --script stark_lightning_X_trt --config baseline_rephead_4_lite_search5 --save_dir . --mode single" for training stark_lightning_X_trt on LaSOT dataset, the problem comes as follows. Could you help me with this problem? Thank u so much! By the way, I can train ToMP50 in the same python environment. 

checkpoints will be saved to /home/cui/Stark-main/checkpoints
loader <lib.train.data.loader.LTRLoader object at 0x7f21e13b3438>
Training crashed at epoch 1
Traceback (most recent call last):
  File "lib/train/run_training.py", line 104, in <module>
    main()
  File "lib/train/run_training.py", line 101, in main
    distill=args.distill, script_teacher=args.script_teacher, config_teacher=args.config_teacher)
  File "lib/train/run_training.py", line 73, in run_training
    expr_func(settings)
  File "/home/cui/Stark-main/lib/train/../../lib/train/train_script.py", line 118, in run
    trainer.train(cfg.TRAIN.EPOCH, load_latest=False, fail_safe=False)
  File "/home/cui/Stark-main/lib/train/../../lib/train/trainers/base_trainer.py", line 85, in train
    self.train_epoch()
  File "/home/cui/Stark-main/lib/train/../../lib/train/trainers/ltr_trainer.py", line 104, in train_epoch
    self.cycle_dataset(loader)
  File "/home/cui/Stark-main/lib/train/../../lib/train/trainers/ltr_trainer.py", line 63, in cycle_dataset
    for i, data in enumerate(loader, 1):
  File "/home/cui/anaconda3/envs/stark/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/cui/anaconda3/envs/stark/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/cui/anaconda3/envs/stark/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/cui/anaconda3/envs/stark/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/cui/anaconda3/envs/stark/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/cui/anaconda3/envs/stark/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cui/anaconda3/envs/stark/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cui/Stark-main/lib/train/../../lib/train/data/sampler.py", line 98, in __getitem__
    return self.getitem()
  File "/home/cui/Stark-main/lib/train/../../lib/train/data/sampler.py", line 110, in getitem
    dataset = random.choices(self.datasets, self.p_datasets)[0]
  File "/home/cui/anaconda3/envs/stark/lib/python3.6/random.py", line 360, in choices
    raise ValueError('The number of weights does not match the population')
ValueError: The number of weights does not match the population

**Comment by 7854221** [comment]
你好怎么解决哇
